
export const userDetails = [
    {
      empId: 1,
      name: "Ravi Kumar",
      status: "Present",
      modal: {
        Gender: "Male",
        Email: "Ravi@gmail.com",
        Mobile: "9877456122",
        Address: "BBSR",
        Username: "Ravi",
        Password: "Ravi",
        Documents: "",
        Dateofjoin: "01/05/2018",
      },
    },
    {
      empId: 2,
      name: "Pranaya Kumar",
      status: "Present",
      modal: {
        Gender: "Male",
        Email: "Pranaya@gmail.com",
        Mobile: "9877456122",
        Address: "BBSR",
        Username: "Pranaya",
        Password: "Pranaya",
        Documents: "",
        Dateofjoin: "17/05/2018",
      },
    },
    {
      empId: 3,
      name: "Ankit Kumar",
      status: "Absent",
      modal: {
        Gender: "Male",
        Email: "Ankit@gmail.com",
        Mobile: "9877456122",
        Address: "BBSR",
        Username: "Ankit ",
        Password: "Ankit ",
        Documents: "",
        Dateofjoin: "18/05/2018",
      },
    },
  ];
  export const billerDetails = [
    {
      empId: 1,
      name: "Ranvijaya Rastogi",
      status: "Present",
      modal: {
        Gender: "Male",
        Email: "Ranvijaya@gmail.com",
        Mobile: "9877456122",
        Address: "BBSR",
        Username: "Ranvijaya",
        Password: "Ranvijaya",
        Documents: "",
        Dateofjoin: "20/05/2018",
      },
    },
    {
      empId: 2,
      name: "Akhilesh Singh",
      status: "Present",
      modal: {
        Gender: "Male",
        Email: "Akhilesh@gmail.com",
        Mobile: "9877456122",
        Address: "BBSR",
        Username: "Akhilesh",
        Password: "Akhilesh",
        Documents: "",
        Dateofjoin: "01/10/2018",
      },
    },
    {
      empId: 3,
      name: "Suresh Mishra",
      status: "Absent",
      modal: {
        Gender: "Male",
        Email: "Suresh@gmail.com",
        Mobile: "9877456122",
        Address: "BBSR",
        Username: "Suresh",
        Password: "Suresh",
        Documents: "",
        Dateofjoin: "01/05/2018",
      },
    },
  ];

  export const chefDetails = [
    {
      empId: 1,
      name: "Ruturaj Agrawal	",
      status: "Present",
      modal: {
        Gender: "Male",
        Email: "Ranvijaya@gmail.com",
        Mobile: "9877456122",
        Address: "BBSR",
        Username: "Ranvijaya",
        Password: "Ranvijaya",
        Documents: "",
        Dateofjoin: "20/05/2018",
      },
    },
    {
      empId: 2,
      name: "Akhilesh Singh",
      status: "Present",
      modal: {
        Gender: "Male",
        Email: "Akhilesh@gmail.com",
        Mobile: "9877456122",
        Address: "BBSR",
        Username: "Akhilesh",
        Password: "Akhilesh",
        Documents: "",
        Dateofjoin: "01/10/2018",
      },
    },
    {
      empId: 3,
      name: "Suresh Mishra",
      status: "Absent",
      modal: {
        Gender: "Male",
        Email: "Suresh@gmail.com",
        Mobile: "9877456122",
        Address: "BBSR",
        Username: "Suresh",
        Password: "Suresh",
        Documents: "",
        Dateofjoin: "01/05/2018",
      },
    },
  ];

  export const workerDetails = [
    {
      empId: 1,
      name: "Rajesh kumar",
      status: "Present",
      modal: {
        Gender: "Male",
        Email: "Rajesh@gmail.com",
        Mobile: "9877456122",
        Address: "BBSR",
        Username: "Rajesh",
        Password: "Rajesh",
        Documents: "",
        Dateofjoin: "20/05/2018",
      },
    },
    {
      empId: 2,
      name: "Juned Raj",
      status: "Present",
      modal: {
        Gender: "Male",
        Email: "Juned@gmail.com",
        Mobile: "9877456122",
        Address: "BBSR",
        Username: "Juned",
        Password: "Juned",
        Documents: "",
        Dateofjoin: "01/10/2018",
      },
    },
    {
      empId: 3,
      name: "Satu Swain",
      status: "Absent",
      modal: {
        Gender: "Male",
        Email: "Satu@gmail.com",
        Mobile: "9877456122",
        Address: "BBSR",
        Username: "Satu",
        Password: "Satu",
        Documents: "",
        Dateofjoin: "01/05/2018",
      },
    },
  ];

