export var waiter = [
  {
    name: "Ashok Kumar",
    status: "Active",
    ordertaken: "5",
    tableno: "1",
    orderdetails: ["rice", "dal", "paneer", "chicken"],
  },
  {
    name: "Vinod Raj",
    status: "Active",
    ordertaken: "10",
    tableno: "5",
    orderdetails: ["masala papad", "tandoor chicken", "coldrink", "dry chana"],
  },
  { name: "Akash  Sahu", status: "Inactive" },
  {
    name: "Sunil Kumar",
    status: "Active",
    ordertaken: "7",
    tableno: "4",
    orderdetails: ["rice", "dal", "mutton", "egg", "salad"],
  },
  { name: "Laxman Hota", status: "Inactive" },
  { name: "Santosh Panda", status: "Inactive" },
  {
    name: "Rakesh Pradhan",
    status: "Active",
    ordertaken: "3",
    tableno: "2",
    orderdetails: ["friedrice", "manchurian", "dry chana"],
  },
  { name: "Sagar Panda", status: "Inactive" },
  {
    name: "Suraj Pradhan",
    status: "Active",
    ordertaken: "3",
    tableno: "5",
    orderdetails: ["friedrice", "manchurian", "dry chana"],
  },
];
